# Generated by Django 4.2.6 on 2023-10-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal_stockpile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='date_removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
